### ISSUE TITLE
Post Request when proxied via H2o2 does not send data to auditing

### ISSUE THREAD

**Issue by athankapl88** [denlap007/hapi-audit-rest#4]
When submitting data via H2o2 Proxy Plugin application runs into "throw new Error(`Cannot read streamed response on ${routeEndpoint}`);".

Audit is successful if we add onResponse function in proxy route options

**Comment by denlap007** [comment]
When a **POST request is streamed** to an upstream server, there is **no access to the payload** and an audit log document cannot be created. An error is thrown to notify regarding the endpoint that was not audited.

Related info and flow diagram available on [readme](https://github.com/denlap007/hapi-audit-rest/blob/master/README.md#post---scope-resource)
